# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-25 08:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authority', '0002_auto_20160425_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=800, verbose_name='\u03a4\u039c\u0397\u039c\u0391')),
                ('authority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authority.Authority')),
            ],
        ),
    ]
