# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-11 06:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('division', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='authority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authority.Authority', verbose_name='\u0394\u0399\u0395\u03a5\u0398\u03a5\u039d\u03a3\u0397'),
        ),
    ]
