# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-11 06:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authority', '0002_auto_20160425_1106'),
        ('division', '0002_auto_20160511_0908'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=800, verbose_name='\u039f\u039d\u039f\u039c\u0391\u03a4\u0395\u03a0\u03a9\u039d\u03a5\u039c\u039f')),
                ('authority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authority.Authority', verbose_name='\u0394\u0399\u0395\u03a5\u0398\u03a5\u039d\u03a3\u0397')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='division.Division', verbose_name='\u03a4\u039c\u0397\u039c\u0391')),
            ],
        ),
    ]
