# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-25 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=300, verbose_name='\u039a\u0391\u03a4\u0397\u0393\u039f\u03a1\u0399\u0391'),
        ),
    ]
