# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-12 07:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0002_auto_20160425_1106'),
        ('authority', '0002_auto_20160425_1106'),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka', models.CharField(max_length=300, verbose_name='\u039c\u0391\u03a1\u039a\u0391')),
                ('montelo', models.CharField(max_length=300, verbose_name='\u039c\u039f\u039d\u03a4\u0395\u039b\u039f')),
                ('seiriakos', models.CharField(max_length=300, verbose_name='\u03a3\u0395\u0399\u03a1\u0399\u0391\u039a\u039f\u03a3')),
                ('leitourgiko', models.CharField(max_length=100, verbose_name='\u039b\u0395\u0399\u03a4\u039f\u03a5\u03a1\u0393\u0399\u039a\u039f')),
                ('num_apografis', models.CharField(max_length=200, verbose_name='\u0391\u03a1\u0399\u0398\u039c\u039f\u03a3 \u0391\u03a0\u039f\u0393\u03a1\u0391\u03a6\u0397\u03a3')),
                ('sxolia', models.CharField(max_length=300, verbose_name='\u03a0\u0391\u03a1\u0391\u03a4\u0397\u03a1\u0397\u03a3\u0395\u0399\u03a3')),
                ('authority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authority.Authority', verbose_name='\u0394\u0399\u0395\u03a5\u0398\u03a5\u039d\u03a3\u0397')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category', verbose_name='\u039a\u0391\u03a4\u0397\u0393\u039f\u03a1\u0399\u0391')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Employee', verbose_name='\u03a0\u03a1\u039f\u03a3\u03a9\u03a0\u0399\u039a\u039f')),
            ],
        ),
    ]
