# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-17 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='num_apografis',
            field=models.CharField(max_length=200, verbose_name='\u039a\u03a9\u0394\u0399\u039a\u039f\u03a3 \u039b\u0395\u0399\u03a4\u039f\u03a5\u03a1\u0393\u0399\u039a\u039f\u03a5'),
        ),
    ]
