# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-25 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authority',
            name='name',
            field=models.CharField(max_length=600, verbose_name='\u0394\u0399\u0395\u03a5\u0398\u03a5\u039d\u03a3\u0397'),
        ),
    ]
